
/* AUTO GENERATED classes for tpdp memory structures */

#pragma once

typedef unsigned char       undefined;
typedef unsigned char       byte;
typedef unsigned int        dword;
typedef long long           longlong;
typedef char                sbyte;
typedef unsigned char       uchar;
typedef unsigned int        uint;
typedef unsigned long       ulong;
typedef unsigned char       undefined1;
typedef unsigned short      undefined2;
typedef unsigned int        undefined4;
typedef unsigned long long  undefined6;
typedef unsigned long long  undefined8;
typedef unsigned short      ushort;
typedef unsigned short      word;

#pragma pack(push, 1)
typedef struct BattleData BattleData, *PBattleData;

typedef struct PartyPuppet PartyPuppet, *PPartyPuppet;

typedef struct BattleState BattleState, *PBattleState;

struct BattleState {
    sbyte stat_modifiers[6];
    sbyte crit_rate;
    sbyte evasion;
    sbyte accuracy;
    ushort active_puppet_id;
    byte active_style_index;
    byte active_level;
    char active_nickname[32];
    byte active_costume_index;
    float field_0x2e;
    float field_0x32;
    float field_0x36;
    float field_0x3a;
    float field_0x3e;
    float field_0x42;
    undefined4 field_0x46;
    float field_0x4a;
    int field_0x4e;
    float field_0x52;
    undefined4 field_0x56;
    float field_0x5a;
    undefined4 field_0x5e;
    float field_0x62;
    undefined field_0x66;
    float field_0x67;
    float field_0x6b;
    uint active_player;
    struct PartyPuppet * active_puppet;
    short base_puppet_id;
    undefined field_0x79;
    short active_ability;
    undefined field_0x7c;
    undefined field_0x7d;
    undefined field_0x7e;
    undefined field_0x7f;
    undefined field_0x80;
    undefined field_0x81;
    undefined field_0x82;
    undefined field_0x83;
    undefined field_0x84;
    undefined field_0x85;
    undefined field_0x86;
    undefined field_0x87;
    undefined field_0x88;
    undefined field_0x89;
    undefined field_0x8a;
    undefined field_0x8b;
    undefined field_0x8c;
    undefined field_0x8d;
    undefined field_0x8e;
    undefined field_0x8f;
    undefined field_0x90;
    byte puppet_sp[4];
    undefined field_0x95;
    undefined field_0x96;
    undefined field_0x97;
    undefined field_0x98;
    byte active_type1;
    byte active_type2;
    short active_held_item;
    byte field_0x9d;
    undefined field_0x9e;
    undefined field_0x9f;
    undefined field_0xa0;
    undefined field_0xa1;
    undefined field_0xa2;
    undefined field_0xa3;
    undefined field_0xa4;
    undefined field_0xa5;
    undefined field_0xa6;
    undefined field_0xa7;
    undefined field_0xa8;
    undefined field_0xa9;
    undefined field_0xaa;
    undefined field_0xab;
    bool switched_puppet;
    int num_turns;
    byte field_0xb1;
    undefined field_0xb2;
    undefined field_0xb3;
    undefined field_0xb4;
    undefined field_0xb5;
    undefined field_0xb6;
    undefined field_0xb7;
    undefined field_0xb8;
    undefined field_0xb9;
    undefined field_0xba;
    undefined field_0xbb;
    undefined field_0xbc;
    undefined field_0xbd;
    undefined field_0xbe;
    undefined field_0xbf;
    undefined field_0xc0;
    undefined field_0xc1;
    undefined field_0xc2;
    int field_0xc3;
    undefined field_0xc7;
    undefined field_0xc8;
    undefined field_0xc9;
    undefined field_0xca;
    undefined field_0xcb;
    undefined field_0xcc;
    undefined field_0xcd;
    undefined field_0xce;
    undefined field_0xcf;
    undefined field_0xd0;
    undefined field_0xd1;
    undefined field_0xd2;
    undefined field_0xd3;
    int field_0xd4;
    undefined field_0xd8;
    undefined field_0xd9;
    undefined field_0xda;
    undefined field_0xdb;
    undefined field_0xdc;
    undefined field_0xdd;
    undefined field_0xde;
    undefined field_0xdf;
    undefined field_0xe0;
    undefined field_0xe1;
    bool field_0xe2;
    undefined field_0xe3;
    undefined field_0xe4;
    undefined field_0xe5;
    undefined field_0xe6;
    undefined field_0xe7;
    undefined field_0xe8;
    undefined2 unk_hazard1;
    int trap_turns;
    undefined4 unk_hazard2;
    undefined field_0xf3;
    undefined field_0xf4;
    undefined field_0xf5;
    undefined field_0xf6;
    undefined field_0xf7;
    undefined field_0xf8;
    undefined field_0xf9;
    undefined field_0xfa;
    undefined field_0xfb;
    undefined field_0xfc;
    undefined field_0xfd;
    int field_0xfe;
    int field_0x102;
    int field_0x106;
    undefined field_0x10a;
    bool drain_seed;
    undefined field_0x10c;
    undefined field_0x10d;
    undefined field_0x10e;
    undefined field_0x10f;
    undefined field_0x110;
    undefined field_0x111;
    undefined field_0x112;
    undefined field_0x113;
    undefined field_0x114;
    undefined field_0x115;
    undefined field_0x116;
    undefined field_0x117;
    undefined field_0x118;
    undefined field_0x119;
    undefined field_0x11a;
    int field_0x11b;
    int field_0x11f;
    int field_0x123;
    undefined field_0x127;
    undefined field_0x128;
    undefined field_0x129;
    undefined field_0x12a;
    undefined field_0x12b;
    undefined field_0x12c;
    undefined field_0x12d;
    undefined field_0x12e;
    undefined field_0x12f;
    undefined field_0x130;
    undefined field_0x131;
    undefined field_0x132;
    undefined field_0x133;
    int num_attacks;
    undefined field_0x138;
    undefined field_0x139;
    undefined field_0x13a;
    undefined field_0x13b;
    short dmg_dealt;
    undefined field_0x13e;
    undefined field_0x13f;
    undefined field_0x140;
    undefined field_0x141;
    undefined field_0x142;
    undefined field_0x143;
    short field_0x144;
    short active_skill_id;
    undefined field_0x148;
    undefined field_0x149;
    short field_0x14a;
    int field_0x14c;
    undefined field_0x150;
    undefined field_0x151;
    undefined field_0x152;
    undefined field_0x153;
    int field_0x154;
    undefined field_0x158;
    undefined field_0x159;
    undefined field_0x15a;
    undefined field_0x15b;
    undefined field_0x15c;
    undefined field_0x15d;
    undefined field_0x15e;
    byte field_0x15f;
    undefined field_0x160;
    undefined field_0x161;
    undefined field_0x162;
    undefined field_0x163;
    undefined field_0x164;
    undefined field_0x165;
    ushort * consumed_item_ptr;
    undefined field_0x16a;
    undefined field_0x16b;
    undefined field_0x16c;
    undefined field_0x16d;
    byte field_0x16e;
    int field_0x16f;
    int field_0x173;
    undefined field_0x177;
    undefined field_0x178;
    undefined field_0x179;
    undefined field_0x17a;
    undefined field_0x17b;
    undefined field_0x17c;
    undefined field_0x17d;
    undefined field_0x17e;
    undefined field_0x17f;
    undefined field_0x180;
    undefined field_0x181;
    undefined field_0x182;
    undefined field_0x183;
    int turn_order;
    undefined field_0x188;
    undefined field_0x189;
    undefined field_0x18a;
    undefined field_0x18b;
    undefined field_0x18c;
    undefined field_0x18d;
    undefined field_0x18e;
    undefined field_0x18f;
    undefined field_0x190;
    undefined field_0x191;
    undefined field_0x192;
    undefined field_0x193;
    undefined field_0x194;
    bool stealth_trap;
    bool bind_trap;
    int num_poison_trap;
    int num_mine_trap;
};

struct PartyPuppet {
    uint trainer_id;
    uint secret_id;
    char trainer_name[32];
    ushort caught_location;
    byte caught_year;
    byte caught_month;
    byte caught_day;
    byte caught_hour;
    byte caught_minute;
    char puppet_nickname[32];
    ushort puppet_id;
    byte style_index;
    byte ability_index;
    byte mark;
    byte ivs[3];
    undefined field_0x57;
    uint experience;
    ushort happiness;
    ushort pp;
    byte costume_index;
    byte evs[6];
    ushort held_item;
    ushort skills[4];
    bool heart_mark;
    undefined field_0x72;
    undefined field_0x73;
    undefined field_0x74;
    undefined field_0x75;
    undefined field_0x76;
    undefined field_0x77;
    undefined field_0x78;
    undefined field_0x79;
    undefined field_0x7a;
    undefined field_0x7b;
    undefined field_0x7c;
    undefined field_0x7d;
    undefined field_0x7e;
    undefined field_0x7f;
    undefined field_0x80;
    undefined field_0x81;
    undefined field_0x82;
    undefined field_0x83;
    undefined field_0x84;
    undefined field_0x85;
    undefined field_0x86;
    undefined field_0x87;
    undefined field_0x88;
    undefined field_0x89;
    undefined field_0x8a;
    undefined field_0x8b;
    undefined field_0x8c;
    undefined field_0x8d;
    undefined field_0x8e;
    undefined field_0x8f;
    undefined field_0x90;
    uint checksum;
    byte level;
    ushort hp;
    byte sp[4];
    byte status_effects[2];
    byte stopped_turns;
    undefined field_0x9f;
    undefined field_0xa0;
    ushort field_0xa1;
    undefined field_0xa3;
    undefined field_0xa4;
};

struct BattleData {
    undefined field_0x0;
    char player_name[32];
    int active_player;
    byte active_puppet_index;
    struct PartyPuppet puppets[6];
    struct BattleState state;
};

typedef struct EncryptedPuppet EncryptedPuppet, *PEncryptedPuppet;

struct EncryptedPuppet {
    uint trainer_id;
    uint secret_id;
    char trainer_name[32];
    ushort caught_location;
    byte caught_year;
    byte caught_month;
    byte caught_day;
    byte caught_hour;
    byte caught_minute;
    char puppet_nickname[32];
    ushort puppet_id;
    byte style_index;
    byte ability_index;
    byte mark;
    byte ivs[3];
    undefined field_0x57;
    uint experience;
    ushort happiness;
    ushort pp;
    byte costume_index;
    byte evs[6];
    ushort held_item;
    ushort skills[4];
    bool heart_mark;
    undefined field_0x72;
    undefined field_0x73;
    undefined field_0x74;
    undefined field_0x75;
    undefined field_0x76;
    undefined field_0x77;
    undefined field_0x78;
    undefined field_0x79;
    undefined field_0x7a;
    undefined field_0x7b;
    undefined field_0x7c;
    undefined field_0x7d;
    undefined field_0x7e;
    undefined field_0x7f;
    undefined field_0x80;
    undefined field_0x81;
    undefined field_0x82;
    undefined field_0x83;
    undefined field_0x84;
    undefined field_0x85;
    undefined field_0x86;
    undefined field_0x87;
    undefined field_0x88;
    undefined field_0x89;
    undefined field_0x8a;
    undefined field_0x8b;
    undefined field_0x8c;
    undefined field_0x8d;
    undefined field_0x8e;
    undefined field_0x8f;
    undefined field_0x90;
};

typedef struct PuppetData PuppetData, *PPuppetData;

typedef struct PuppetStyleData PuppetStyleData, *PPuppetStyleData;

struct PuppetStyleData {
    byte style_type;
    byte element1;
    byte element2;
    byte base_stats[6];
    ushort abilities[2];
    undefined field_0xd;
    undefined field_0xe;
    undefined field_0xf;
    undefined field_0x10;
    ushort style_skills[11];
    undefined field_0x27;
    undefined field_0x28;
    undefined field_0x29;
    undefined field_0x2a;
    undefined field_0x2b;
    undefined field_0x2c;
    ushort lvl_100_skill;
    undefined field_0x2f;
    undefined field_0x30;
    byte compat_bitfield[16];
    ushort level_70_skills[8];
    undefined field_0x51;
    undefined field_0x52;
    undefined field_0x53;
    undefined field_0x54;
    undefined field_0x55;
    undefined field_0x56;
    undefined field_0x57;
    undefined field_0x58;
    undefined field_0x59;
    undefined field_0x5a;
    undefined field_0x5b;
    undefined field_0x5c;
    undefined field_0x5d;
    undefined field_0x5e;
    undefined field_0x5f;
    undefined field_0x60;
    undefined field_0x61;
    undefined field_0x62;
    undefined field_0x63;
    undefined field_0x64;
};

struct PuppetData {
    char field_0x0[32];
    byte cost;
    ushort base_skills[5];
    ushort item_drop_table[4];
    ushort puppetdex_index;
    undefined field_0x35;
    undefined field_0x36;
    undefined field_0x37;
    undefined field_0x38;
    undefined field_0x39;
    undefined field_0x3a;
    undefined field_0x3b;
    undefined field_0x3c;
    undefined field_0x3d;
    undefined field_0x3e;
    undefined field_0x3f;
    undefined field_0x40;
    undefined field_0x41;
    undefined field_0x42;
    undefined field_0x43;
    undefined field_0x44;
    undefined field_0x45;
    undefined field_0x46;
    undefined field_0x47;
    undefined field_0x48;
    undefined field_0x49;
    undefined field_0x4a;
    undefined field_0x4b;
    undefined field_0x4c;
    undefined field_0x4d;
    undefined field_0x4e;
    undefined field_0x4f;
    undefined field_0x50;
    undefined field_0x51;
    undefined field_0x52;
    undefined field_0x53;
    undefined field_0x54;
    undefined field_0x55;
    undefined field_0x56;
    undefined field_0x57;
    undefined field_0x58;
    undefined field_0x59;
    undefined field_0x5a;
    undefined field_0x5b;
    undefined field_0x5c;
    struct PuppetStyleData styles[4];
};

typedef struct SkillData SkillData, *PSkillData;

struct SkillData {
    char name[32];
    byte element;
    byte power;
    byte accuracy;
    byte sp;
    sbyte priority;
    byte type;
    undefined field_0x26;
    ushort effect_id;
    byte effect_chance;
    byte classification;
    byte target;
    ushort id;
    undefined field_0x2e;
    undefined field_0x2f;
    undefined field_0x30;
    undefined field_0x31;
    undefined field_0x32;
    undefined field_0x33;
    undefined field_0x34;
    undefined field_0x35;
    undefined field_0x36;
    undefined field_0x37;
    undefined field_0x38;
    undefined field_0x39;
    undefined field_0x3a;
    undefined field_0x3b;
    undefined field_0x3c;
    undefined field_0x3d;
    undefined field_0x3e;
    undefined field_0x3f;
    undefined field_0x40;
    undefined field_0x41;
    undefined field_0x42;
    undefined field_0x43;
    undefined field_0x44;
    undefined field_0x45;
    undefined field_0x46;
    undefined field_0x47;
    undefined field_0x48;
    undefined field_0x49;
    undefined field_0x4a;
    undefined field_0x4b;
    undefined field_0x4c;
    undefined field_0x4d;
    undefined field_0x4e;
    undefined field_0x4f;
    undefined field_0x50;
    undefined field_0x51;
    undefined field_0x52;
    undefined field_0x53;
    undefined field_0x54;
    undefined field_0x55;
    undefined field_0x56;
    undefined field_0x57;
    undefined field_0x58;
    undefined field_0x59;
    undefined field_0x5a;
    undefined field_0x5b;
    undefined field_0x5c;
    undefined field_0x5d;
    undefined field_0x5e;
    undefined field_0x5f;
    undefined field_0x60;
    undefined field_0x61;
    undefined field_0x62;
    undefined field_0x63;
    undefined field_0x64;
    undefined field_0x65;
    undefined field_0x66;
    undefined field_0x67;
    undefined field_0x68;
    undefined field_0x69;
    undefined field_0x6a;
    undefined field_0x6b;
    undefined field_0x6c;
    undefined field_0x6d;
    undefined field_0x6e;
    undefined field_0x6f;
    undefined field_0x70;
    undefined field_0x71;
    undefined field_0x72;
    undefined field_0x73;
    undefined field_0x74;
    undefined field_0x75;
    undefined field_0x76;
};

typedef struct TerrainState TerrainState, *PTerrainState;

struct TerrainState {
    byte weather_type;
    byte terrain_type;
    undefined field_0x2;
    undefined field_0x3;
    uint weather_duration;
    uint terrain_duration;
};
#pragma pack(pop)

